version: "3.7"

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "<api-id>"
      TELEGRAM_API_HASH: "<api-hash>"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"
  telegram-bot-upload:
    image: telegram-upload/bot
    build:
      dockerfile: ./Dockerfile
    environment:
      USER_ID: "<user-id>"
      API_URL: "<api-url>"
      TOKEN: "<token>"
    depends_on:
      - telegram-bot-api
volumes:
  telegram-bot-api-data:
